MarketPanel/ViewComponents/UserInfoViewComponent.cs
using MarketPanel.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MarketPanel.ViewComponents;

public class UserInfoViewComponent : ViewComponent
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;

    public UserInfoViewComponent(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        string email = "";

        if (_signInManager.IsSignedIn(HttpContext.User))
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            email = user.Email;
        }

        return View("Default", email);
    }
}

MarketPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Market Panel</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/Purple/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/Purple/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="/Purple/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/Purple/assets/vendors/font-awesome/css/font-awesome.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="/Purple/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" type="image/png" sizes="512x512" href="/Purple/assets/images/favicon_512x512.png">
</head>
<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
                <a class="navbar-brand brand-logo" href="/Home/Index"><img src="/Purple/assets/images/Logo.svg" style="height: 140px; width: auto;" alt="logo"></a>
                <a class="navbar-brand brand-logo-mini" href="/Home/Index"><img src="/Purple/assets/images/Logo-mini.svg" style="height: 70px; width: auto;" alt="logo"></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>

                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                            @*<div class="nav-profile-img">
                                    <img src="/Purple/assets/images/faces/face1.jpg" alt="image">
                                    <span class="availability-status online"></span>
                                </div>*@
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">
                                    @await Component.InvokeAsync("UserInfo")
                                </p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <form id="logoutForm" method="post" asp-action="Logout" asp-controller="Account" style="display: none;"></form>
                            <a class="dropdown-item" href="javascript:void(0)" onclick="$('#logoutForm').submit();">
                                <i class="mdi mdi-logout me-2 text-primary"></i> Çıkış 
                            </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:../../partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Index">
                            <span class="menu-title">Ana Sayfa</span>
                            <i class="mdi mdi-home menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                            <span class="menu-title">Tanımlar</span>
                            <i class="menu-arrow"></i>
                            <i class="mdi mdi-crosshairs-gps menu-icon"></i>
                        </a>
                        <div class="collapse" id="ui-basic">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link" href="/Category/MyCategories">Kategoriler</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/Product/MyProducts">Ürünler</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">
                            <span class="menu-title">Hareketler</span>
                            <i class="menu-arrow"></i>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                        <div class="collapse" id="icons">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item">
                                    <a class="nav-link" href="/SaleItem/MySaleItems">Satışlar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/SaleDocument/MySaleDocuments">Satış Evraklarım</a>
                                </li>
                            </ul>
                        </div>
                    </li>

                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:../../partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">© 2025 <a href="https://github.com/zehrtunc" target="_blank">Zehra Tunç</a>Tüm hakları saklıdır.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Made by Zehra Tunç<i class="mdi mdi-heart text-danger"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/Purple/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/Purple/assets/js/off-canvas.js"></script>
    <script src="/Purple/assets/js/misc.js"></script>
    <script src="/Purple/assets/js/settings.js"></script>
    <script src="/Purple/assets/js/todolist.js"></script>
    <script src="/Purple/assets/js/jquery.cookie.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <!-- End custom js for this page -->

</body>
</html>