MarketPanel/Models/Entities/SaleItem.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace MarketPanel.Models.Entities;

public class SaleItem
{
    public long Id { get; set; }

    [Required]
    public int Quantity { get; set; }

    [Required]
    [Precision(18,2)]
    public decimal UnitPrice { get; set; }

    [Required]
    [Precision(5,2)]
    public decimal VATRate { get; set; } //KDV ratio

    [Required]
    [Precision(18,2)]
    public decimal Discount { get; set; } //Iskonto

    [Required]
    [Precision(18,2)]
    public decimal Total { get; set; } //o urun icin Total


    public long? SaleDocumentId { get; set; }
    public virtual SaleDocument SaleDocument { get; set; }

    public long ProductId { get; set; }
    public virtual Product Product { get; set; }
}

MarketPanel/Models/ViewModels/SaleItemViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarketPanel.Models.ViewModels;

public class SaleItemViewModel
{
    public long Id { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal VATRate { get; set; }
    public decimal Discount { get; set; }
    public long ProductId { get; set; }

    public List<SelectListItem>? Products { get; set; }

}

MarketPanel/Controllers/SaleDocumentController.cs
using MarketPanel.Models.ViewModels;
using MarketPanel.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MarketPanel.Controllers
{
    public class SaleDocumentController : Controller
    {
        private readonly ISaleDocumentService _saleDocumentService;

        public SaleDocumentController(ISaleDocumentService saleDocumentService)
        {
            _saleDocumentService = saleDocumentService;
        }

        public async Task<IActionResult> MySaleDocuments()
        {
            var model = await _saleDocumentService.GetAllAsync();

            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new SaleDocumentAddViewModel
            {
                SaleItemIds = new List<long>() // null olmamasi icin bos liste 
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(SaleDocumentAddViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            try
            {
                var result = await _saleDocumentService.CreateAsync(model);
                if (result) return RedirectToAction("MySaleDocuments");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Satış evrağı oluşturulurken bir hata oluştu.");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long id)
        {
            var model = await _saleDocumentService.GetByIdAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SaleDocumentViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            try
            {
                var result = await _saleDocumentService.UpdateAsync(model);
                if (result) return RedirectToAction("MySaleDocuments");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Satış evrağı güncellenirken bir hata oluştu.");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(long id)
        {
            var model = await _saleDocumentService.DetailAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(long id)
        {
            try
            {
                var result = await _saleDocumentService.DeleteAsync(id);
                if (result) return RedirectToAction("MySaleDocuments");
            }
            catch(Exception)
            {
                ModelState.AddModelError("", "Satış evrağı silinirken bir hata oluştu.");
            }

            return RedirectToAction("MySaleDocuments");
        }

    }
}

MarketPanel/Controllers/SaleItemController.cs
using MarketPanel.Models.ViewModels;
using MarketPanel.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MarketPanel.Controllers;

public class SaleItemController : Controller
{
    private readonly ISaleItemService _saleItemService;



    public SaleItemController(ISaleItemService saleItemService)
    {
        _saleItemService = saleItemService;

    }
    public async Task<IActionResult> MySaleItems()
    {
        var model = await _saleItemService.GetAllAsync();
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Add()
    {
        //Yeni bir model olustur ve modelin Products listesine veritabanindan Product nesnesinden cektigin listesini ata.
        var model = new SaleItemViewModel
        {
            Products = await _saleItemService.GetProductsAsync(),
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Add(SaleItemViewModel model)
    {
        if (!ModelState.IsValid)
        {
            model.Products = await _saleItemService.GetProductsAsync();
            return View(model);
        }
        try
        {
            var result = await _saleItemService.CreateAsync(model);
            if(result) return RedirectToAction("MySaleItems");
        }
        catch(Exception)
        {
            ModelState.AddModelError("", "Satış eklenirken bir hata oluştu.");
        }

        model.Products = await _saleItemService.GetProductsAsync();
        return View(model);

    }

    [HttpGet]
    public async Task<IActionResult> Edit(long id)
    {
        var model = await _saleItemService.GetByIdAsync(id);

        model.Products = await _saleItemService.GetProductsAsync();

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(SaleItemViewModel model)
    {
        if (!ModelState.IsValid)
        {
            model.Products = await _saleItemService.GetProductsAsync();
            return View(model);
        }

        try
        {
            var result = await _saleItemService.UpdateAsync(model);
            if (result) return RedirectToAction("MySaleItems");
        }
        catch (Exception)
        {
            ModelState.AddModelError("", "Satış güncellenirken bir hata oluştu.");
        }

        //Update sirasinda islem hata verirse ya da basarisiz olursa
        //Update keraninda Productlarin listelenerek gelebilmesi icin:

        model.Products = await _saleItemService.GetProductsAsync();
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(long id)
    {
        try
        {
            var result = await _saleItemService.DeleteAsync(id);
            if (result) return RedirectToAction("MySaleItems");
        }
        catch(Exception)
        {
            ModelState.AddModelError("", "Satış silinirken bir hata oluştu.");
        }

        return RedirectToAction("MySaleItems");
    }
}

MarketPanel/Views/SaleItem/Add.cshtml
@model MarketPanel.Models.ViewModels.SaleItemViewModel

@{
    ViewData["Title"] = "Add";
}



<div class="contaniner d-flex justify-content-center">
    <div class="card p-4 w-100" style="max-width: 600px;">
        <h2>Satış Ekleme</h2>
        <form asp-action="Add" asp-controller="SaleItem" method="post" class="row">
            <div class="mb-3">
                <label asp-for="ProductId" class="form-label">Ürün</label>
                <select id="productId" asp-for="ProductId" asp-items="Model.Products" class="form-select">
                    <option value="">-- Select a product --</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="quantity" class="form-label">Ürün Adedi</label>
                <input asp-for="Quantity" type="text" class="form-control" id="quantity">
            </div>
            <div class="mb-3">
                <label for="unitPrice" class="form-label">Ürünün Birim Fiyatı</label>
                <input asp-for="UnitPrice" type="text" class="form-control" id="unitPrice">
            </div>
            <div class="mb-3">
                <label for="vatRate" class="form-label">Kdv Oranı</label>
                <input asp-for="VATRate" type="text" class="form-control" id="vatRate">
            </div>
            <div class="mb-3">
                <label for="discount" class="form-label">Ürün İndirimi</label>
                <input asp-for="Discount" type="text" class="form-control" id="discount">
            </div>
            <button type="submit" class="btn btn-gradient-primary w-100">Ekle</button>
        </form>
    </div>
    
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {

        $('#productId').on('change', function () {
            var productId = $(this).val();

            if (productId) {
                $.ajax({
                    url: '/Product/Get',
                    type: 'GET',
                    data: { id: productId },
                    success: function (response) {
                        if (response.success) {
                            $('#unitPrice').val(response.price);
                        }
                        else {
                            $('#unitPrice').val('');
                            alert("Ürün fiyatı alınamadı.")
                        }
                    },
                    error: function () {
                        alert("Bir hata oluştu.")
                    }
                });
            }
            else {
                $('#unitPrice').val('');
            }
        });
    });
</script>

MarketPanel/Views/SaleItem/Edit.cshtml
@model MarketPanel.Models.ViewModels.SaleItemViewModel

@{
    ViewData["Title"] = "Edit";
}



<div class="container d-flex justify-content-center">
    <div class="card p-4 w-100" style="max-width: 600px;">
        <h2>Satış Düzenle</h2>
        <form asp-action="Edit" asp-controller="SaleItem" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group mb-3">
                <label asp-for="ProductId" class="form-label">Ürün</label>
                <select asp-for="ProductId" asp-items="Model.Products" class="form-select">
                    <option value="">-- Select a product --</option>
                </select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Quantity" class="form-label">Ürün Adedi</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="UnitPrice" class="form-label">Ürünün Birim Fiyatı</label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="VATRate" class="form-label">Kdv Oranı</label>
                <input asp-for="VATRate" class="form-control" />
                <span asp-validation-for="VATRate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Discount" class="form-label">Ürünün indirimi</label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-gradient-primary">Kaydet</button>
            <a asp-action="MySaleItems" class="btn btn-gradient-dark">Vazgeç</a>
        </form>
    </div>
   
</div>

MarketPanel/Views/SaleItem/MySaleItems.cshtml
@model List<MarketPanel.Models.ViewModels.SaleItemListViewModel>

@{
    ViewData["Title"] = "MySaleItems";
}


<form method="post" asp-action="Add" asp-controller="SaleDocument">
    <div class="container card">
        <div class="d-flex justify-content-between align-items-center m-3 mb-3">
            <h2>Satışlarım</h2>
            <a href="/SaleItem/Add" class="btn btn-gradient-primary">+ Satış Ekle</a>
        </div>

        <table class="table">
            <thead class="table-light">
                <tr>
                    <th style="width: 5%;"></th>
                    <th style="width: 15%;">Ürün İsmi</th>
                    <th style="width: 15%;">Ürün Adedi</th>
                    <th style="width: 15%;">Birim Fiyatı</th>
                    <th style="width: 15%;">Kdv Oranı</th>
                    <th style="width: 15%;">İndirim</th>
                    <th style="width: 15%;">Ürünün Net Fiyatı</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var saleItem in Model)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="SaleItemIds" value="@saleItem.Id" />
                        </td>
                        <td>@saleItem.ProductName</td>
                        <td>@saleItem.Quantity</td>
                        <td>@saleItem.UnitPrice.ToString("C")</td>
                        <td>@saleItem.VATRate</td>
                        <td>@saleItem.Discount</td>
                        <td>@saleItem.Total.ToString("C")</td>
                        <td>
                            <a href="/SaleItem/Edit/@saleItem.Id" class="btn btn-gradient-warning">Düzenle</a>
                        </td>
                        <td>
                            <form asp-action="Delete" asp-controller="SaleItem" method="post">
                                <input type="hidden" value="@saleItem.Id" name="id" />
                                <button type="submit" class="btn btn-danger">Sil</button>
                            </form>
                        <td/>
                    </tr>


                }
            </tbody>
        </table>
        <div class="mt-3 d-grid gap-2 mb-3" style="width: 20%;">
            <button type="submit" class="btn btn-danger"> + Satış Dökümanı Oluştur</button>
        </div>
        
    </div>
</form>